
geekdocToC: 3
geekdocTagsToMenu: true

geekdocRepo: https://github.com/kjetilfjellheim/rust_algorithms

geekdocSearch: true
geekdocSearchShowParent: true
geekdocSearchShowDescription: true

geekdocLegalNotice: https://github.com/kjetilfjellheim/rust_algorithms/blob/main/LICENSE

geekdocDarkModeDim: true