baseURL = "http://localhost"
title = "Rust algorithms"
theme = "hugo-geekdoc"

pluralizeListTitles = false

pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true

geekdocMenuBundle = true
geekdocMenu = true
geekdocMenuPosition = "left"
geekdocMenuWidth = 250
geekdocMenuWidthSmall = 200
geekdocMenuWidthXSmall = 150
geekdocMenuPositionSmall = "top"
geekdocMenuPositionXSmall = "top"

enableRobotsTXT = true

[markup]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "tags"

[params]
  geekdocSubtitle = "A Hugo theme for documentation"
  geekdocDescription = "A Hugo theme for doic"