name: Release
permissions:
  contents: write
on:
  push:
    tags:
      - v[0-9]+.*
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
           GITHUB_TOKEN: ${{ github.token }}
      - name: Install cargo-edit
        run: cargo install cargo-edit
      - name: Install dependencies
        run: cargo fetch
      - name: Set version
        run: cargo set-version 
      - name: Set version        
        run: |
            VERSION=${{ github.ref_name }}
            cargo set-version ${VERSION#v}
      - name: Build apps
        run: cargo build --release     
      - name: Upload apps binaries
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./target/release/busy_beaver
          asset_name: busy-beaver
          asset_content_type: application/octet-stream 
 